project_name: TemporalActionDetection
seed: 42
num_classes: 5
window_size: 32 
device: cuda    # Options: auto, cpu, cuda

data:
  base_dir: Data
  raw_video_dir: ${data.base_dir}/Videos_MERL_Shopping_Dataset
  raw_label_dir: ${data.base_dir}/Labels_MERL_Shopping_Dataset
  processed_dir: ${data.base_dir}/full_videos
  base_model_checkpoints: checkpoints
  rnn_model_checkpoints: rnn_checkpoints
  rnn_processed_data: rnn_processed_data
  logs: logs
  base_best_checkpoint_name: best_model_velocity.pth
  base_resume_checkpoint_name: interim_model_epoch15.pth 
  rnn_best_checkpoint_name: best_rnn_model.pth
  train_inference_raw_name: train_inference_raw.pkl
  val_inference_raw_name: val_inference_raw.pkl
  test_inference_raw_name: test_inference_raw.pkl

preprocessing:
  frame_size: 224
  subsample_factor: 2

feature_extraction:
  pose:
    model_complexity: 1
    min_detection_confidence: 0.5
    
base_model_training:
  resume_training: True
  use_mixed_precision: True
  epochs: 100
  batch_size: 1 
  gradient_accumulation_steps: 4
  optimizer:
    type: AdamW
    lr: 1e-5
    weight_decay: 1e-4
    eps: 1e-4
  scheduler:
    factor: 0.2
    patience: 3
    min_lr: 1e-6
  warmup:
    epochs: 7
    factor: 2.5 
  loss:
    action_weight: 1.5
    start_weight: 1.5
    end_weight: 1.5
    label_smoothing: 0.1
  gradient_clipping:
    max_norm: 7.0
  postprocessing:
    boundary_threshold: 0.11
    class_thresholds: [0.15, 0.15, 0.01, 0.08, 0.15]
    nms_threshold: 0.4
    min_segment_length: 3
  evaluation:
    run_final_evaluation_on_test: True
  debugging:
    debug_detection_enabled: True 
  dataloader:
    num_workers: 4
    batch_size: 1

rnn_data_generation:
  base_checkpoint_to_use: ${data.base_model_checkpoints}/${data.base_best_checkpoint_name}
  dataloader:
    train_batch_size: 4
    val_batch_size: 8
    num_workers: 0
  use_mixed_precision: True

rnn_training:
  model:
    input_size: 15
    num_classes: 6
    type: lstm # 'lstm' or 'gru'
    hidden_size: 128
    num_layers: 2
    dropout_prob: 0.5
    bidirectional: True
  epochs: 50
  batch_size: 16
  optimizer:
    type: AdamW
    lr: 1e-3
  scheduler:
    factor: 0.5
    patience: 5
  early_stopping:
    patience: 10
  dataloader:
    num_workers: 1
  loss:
    ignore_index: -100
  val_batch_size: 32

pipeline_evaluation:
  rnn_checkpoint_to_use: ${data.rnn_model_checkpoints}/${data.rnn_best_checkpoint_name}
  inference_results_pkl: ${data.logs}/${data.test_inference_raw_name}
  visualization:
    enabled: False
    video_id: null
    frames_npz_template: "${data.processed_dir}/test/frames/{video_id}_frames.npz"
    output_video_path: "${data.logs}/visualization_{video_id}.mp4"
    fps: 15
